[package]
name = "gen-vec"
version = "0.1.1"
authors = ["Earl Kennedy <mnenmenth@gmail.com>"]
edition = "2018"
description = "Vector indexed with generational indices"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
